# Generated by Django 4.1.1 on 2025-03-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meme',
        ),
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
